//Exercise #1

<h1> Manage connectivity attempts in Mule app deployment </h1>

When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP connector, that need to connect to an external server. In the event of some connectivity errors, the default behavior is to log a warning message and continue with the deployment of the app, instead of blocking the deployment.

You can modify this behavior by setting a number of reconnection attempts to try after an initial failure and by forcing the deployment to fail when all connection attempts fail.

Set reconnection (`reconnect`) attempts 
Use the Reconnect (`reconnect`) configuration to limit the number of reconnection attempts and the interval at which to execute them. For example, you might set a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms). The default value is 2 reconnection attempts at a frequency of `2000` ms.

Sample code
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----
Fail deployment  (`failsDeployment`) 
Use the Fail Deployment configuration parameter to force the Mule app deployment to fail if the connection with the external server fails when you exhaust the 5 reconnection attempts as defined in this sample code. 

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>

Reconnect Forever (reconnect-forever)
Use this configuration to attempt to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. Defaults to every 2000 ms. This means that there is no limit on the number of retries, so no value for count is specified.

* Example that does not set a limit on the number of reconnection attempts:

Sample configuration
* [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever/>
  </reconnection>
</http:request-connection>
----
